Description:  Infrastructure for EKS Cluster

Parameters:
  EnvName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: DEVENV
  EKSInstanceType:
    Type: String
    Default: t3.medium
    Description: Node group instance type
  MinSize:
    Description: Node group minimal capacity
    Type: Number
    Default: 1
  DesiredCapacity:
    Description: Node group desired capacity
    Type: Number
    Default: 3
  MaxSize:
    Description: Node group maximal capacity
    Type: Number
    Default: 12
  RootVolDevice:
    Type: String
    Default: "/dev/sda1"
  RootVolSize:
    Type: Number
    Default: 22
  ExtraVolDevice:
    Type: String
    Default: "/dev/sdh"
  ExtraVolSize:
    Type: Number
    Default: 1


Resources: 
  NetworkingStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: networking.yaml
      Parameters: 
        EnvName: !Ref EnvName

  K8SCluster: 
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkingStack
    Properties: 
      TemplateURL: k8s.yaml
      Parameters: 
        EnvName: !Ref EnvName

  K8SALB: 
    Type: AWS::CloudFormation::Stack
    DependsOn: K8SCluster
    Properties: 
      TemplateURL: k8s-alb.yaml
      Parameters: 
        EnvName: !Ref EnvName

  K8SNodes: 
    Type: AWS::CloudFormation::Stack
    DependsOn: K8SCluster
    Properties: 
      TemplateURL: k8s-nodegroup.yaml
      Parameters: 
        EnvName: !Ref EnvName
        MinSize: !Ref MinSize
        DesiredCapacity: !Ref DesiredCapacity
        MaxSize: !Ref MaxSize
        EKSInstanceType: !Ref EKSInstanceType
        

Outputs:
  EnvName:
    Value: !Ref EnvName
  
#  KeyPairName:
#    Value: !Ref KeyPairName
#    Export:
#      Name: !Sub "BC::${EnvName}::KEYPAIR" 

# cheat sheet
# export BC_DISTBKT=$(aws cloudformation list-exports --query "Exports[?Name=='BC::${ENV_NAME}::DISTBKT'].Value" --output=text)
# aws cloudformation package --template-file main.yaml --s3-bucket $DISTBKT --s3-prefix "cfn_package" --output-template-file main.out.yaml 
# aws cloudformation deploy --template-file main.out.yaml --stack-name bc-stack --capabilities CAPABILITY_NAMED_IAM
# aws cloudformation delete-stack --stack-name bc-stack
