name: bucket_delete

on: delete

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TF_BUCKET: ${{ secrets.TF_BUCKET }}
      TF_REGION: ${{ secrets.TF_REGION }}
      BRANCH_NAME: ${{ github.event.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Debug variables
        run: |
          echo "BRANCH_NAME=${{ github.event.ref }}" >> $GITHUB_ENV
          echo "Using branch name [$BRANCH_NAME] "

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Terraform version
        run: terraform version
        working-directory: infra/aws/bucket

      - name: Terraform init
        run: |
          TF_KEY="terraform/${BRANCH_NAME}/state"
          echo "Loading state from [$TF_REGION] s3://${TF_BUCKET}/${TF_KEY}"
          terraform init -upgrade -force-copy \
            -backend-config="bucket=$TF_BUCKET" \
            -backend-config="key=$TF_KEY" \
            -backend-config="region=$TF_REGION"
          echo "Terraform initialized"
          sleep 3
          terraform output
          echo "SIMPLE_BUCKET_NAME=$(terraform output simple_bucket_name)" >> $GITHUB_ENV
          echo "Terraform state refreshed"
        working-directory: infra/aws/bucket
        env:
          TF_VAR_branch_name: ${{ env.BRANCH_NAME }}

      - name: Bucket cleanup
        run: |
          echo "Cleanup bucket [${{env.SIMPLE_BUCKET_NAME}}]"
          aws s3api put-bucket-versioning --bucket "${{env.SIMPLE_BUCKET_NAME}}"  --versioning-configuration "Status=Suspended"
          aws s3api delete-bucket-policy --bucket "${{env.SIMPLE_BUCKET_NAME}}"
          aws s3 rm "s3://${{env.SIMPLE_BUCKET_NAME}}" --recursive
        working-directory: infra/aws/bucket

      - name: Terraform destroy
        run: |
          echo "Destroying state from branch [${{ env.BRANCH_NAME }}]"
          terraform destroy -auto-approve
        working-directory: infra/aws/bucket
        env:
          TF_VAR_branch_name: ${{ env.BRANCH_NAME }}
