name: bucket_push

on:
  push:
    branches:
      - 'bucket/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TF_BUCKET: ${{ secrets.TF_BUCKET }}
      TF_REGION: ${{ secrets.TF_REGION }}

    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1.0.1

      - name: Identify branch
        run: echo "Running on branch ${BRANCH_NAME}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Terraform init
        run: |
          TF_KEY="terraform/${BRANCH_NAME}/state"
          echo "Loading state from [$TF_REGION] s3://${TF_BUCKET}/${TF_KEY}"
          terraform init -upgrade -force-copy \
            -backend-config="bucket=$TF_BUCKET" \
            -backend-config="key=$TF_KEY" \
            -backend-config="region=$TF_REGION"
        working-directory: infra/aws/bucket

      - name: Terraform apply
        run: |
          echo "Applying state from branch [$TF_VAR_branch_name]"
          terraform apply -auto-approve
        working-directory: infra/aws/bucket
        env:
          TF_VAR_branch_name: ${{env.BRANCH_NAME}}

      - name: Terraform output
        run: |
          terraform output > terraform_outputs.txt
          cat terraform_outputs.txt
        working-directory: infra/aws/bucket

      - name: S3 Check
        run: |
            BUCKET_NAME=$(terraform output simple_bucket_name)
            echo "aws s3 ls s3://${BUCKET_NAME}"
            echo "aws s3 xs s3://trialh.k8s-blueprints"
            aws s3 ls "s3://$(terraform output simple_bucket_name)"
        working-directory: infra/aws/bucket

      - name: Archive outputs
        uses: actions/upload-artifact@v2
        with:
          name: outputs-txt
          path: infra/aws/bucket/terraform_outputs.txt
