name: bucket_delete

on: delete

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TF_BUCKET: ${{ secrets.TF_BUCKET }}
      TF_REGION: ${{ secrets.TF_REGION }}
      BRANCH_NAME: ${{ github.event.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Debug variables
        run: |
          echo "branch ${BRANCH_NAME}"
          echo "event ref ${{ github.event.ref }}"
          echo "ref type ${{ github.event.ref_type }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Terraform init
        run: |
          TF_KEY="terraform/${BRANCH_NAME}/state"
          echo "Loading state from [$TF_REGION] s3://${TF_BUCKET}/${TF_KEY}"
          terraform init -upgrade -force-copy \
            -backend-config="bucket=$TF_BUCKET" \
            -backend-config="key=$TF_KEY" \
            -backend-config="region=$TF_REGION"
        working-directory: infra/aws/bucket

      - name: Bucket cleanup
        run: |
          BUCKET_NAME=$(terraform output simple_bucket_name)
          echo "Cleanup bucket [$BUCKET_NAME]"
          aws s3api put-bucket-versioning --bucket "$BUCKET_NAME"  --versioning-configuration "Status=Suspended"
          aws s3api delete-bucket-policy --bucket "$BUCKET_NAME"
          aws s3 rm "s3://$BUCKET_NAME" --recursive

      - name: Terraform destroy
        run: |
          echo "Destroying state from branch [$TF_VAR_branch_name]"
          terraform destroy -auto-approve
        working-directory: infra/aws/bucket
        env:
          TF_VAR_branch_name: ${{ env.BRANCH_NAME }}
