name: lint

on:
  push:
    branches:
      - 'lint/**'

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: false
          VALIDATE_SQL: false
          VALIDATE_CSS: false
          VALIDATE_ENV: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_JAVA: false
          VALIDATE_HTML: false
          OUTPUT_FORMAT: tap
          OUTPUT_FOLDER: target/super-linter

      - name: Archive linter results
        uses: actions/upload-artifact@v2
        with:
          name: linter-report
          path: target/super-linter/
